apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: 975050024946.dkr.ecr.us-west-2.amazonaws.com/muni-services/gateway-service:latest
          ports:
            - containerPort: 3003
          env:
            - name: ORDER_SERVICE_URL
              value: "http://order-service:3002"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:3001"
            - name: USER_SERVICE_URL
              value: "http://user-service:3000"
      imagePullSecrets:
        - name: ecr-creds
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    app: gateway-service
  ports:
    - port: 3003
      targetPort: 3003
      nodePort: 30083   # exposed on laptop