apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: 975050024946.dkr.ecr.us-west-2.amazonaws.com/muni-services/product-service:latest
          ports:
            - containerPort: 3001
      imagePullSecrets:
        - name: ecr-creds

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
    - port: 3001
      targetPort: 3001
