# Base image
FROM node:18-alpine

# Set working directory
WORKDIR /

# Copy and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the service port
EXPOSE 3003

# Run the application
CMD ["node", "app.js"]
